### ISSUE TITLE
Initial empty lines are not counted for when loading JSON data

### ISSUE THREAD

**Issue by milasudril** [milasudril/maike#40]

**Comment by milasudril** [comment]
Libjansson does not like streams that only contains whitespace.

**Comment by mk-pmb** [comment]
[This sed script](https://github.com/mk-pmb/midiconstants-csv/blob/free-software-edition/build/extract-maike-meta-keep-lnum.sed) should extract the Maike JSON if there is any and keep the line numbers intact. If there is no Maike JSON, its output should be none (0 bytes).
